# Generated by Django 4.0.3 on 2022-04-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unread1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='unread2',
            field=models.IntegerField(default=0),
        ),
    ]
