# Generated by Django 4.0.3 on 2022-04-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging_System', '0002_chat_unread1_chat_unread2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='has_unread',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
